#lang info
(define collection 'multi)
(define deps '("base" "srfi-lib" ("racket" #:version "8.7")))
(define build-deps '("scribble-lib" "racket-doc" "rackunit-lib"))
(define scribblings '(("unicode-breaks/scribblings/unicode-breaks.scrbl" ())))
(define pkg-desc "Implementations of Unicode Annex #29 break algorithms")
(define version "0.1.14")
(define pkg-authors '(shawnw))
(define license '(Apache-2.0 OR MIT))
(define test-omit-paths '(#rx"scripts" #rx"private" #rx"scribblings"))